const CONFIG = {
  SPREADSHEET_ID: "1sIzswZnMkyRPJejAsE_ylSKzAF0RmFiACP4jYtz-AE0",
  // BURAYA YENİ KOPYALADIĞIN EXEC LİNKİNİ YAPIŞTIR
  API_BASE: "BURAYA_YENI_LINKI_YAPISTIR",
  NOTIF_API_BASE: "BURAYA_YENI_LINKI_YAPISTIR",
  
  SHEET_MAIN: "BÜTÜN OYUNLAR",
  SHEET_FIGURAN: "FİGÜRAN LİSTESİ",
  SHEET_NOTIFS: "BİLDİRİMLER",
  GID: "1233566992",
};
